blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.zapros_new, name='zapros_new'),
    path('worker_list/', views.worker_list, name='worker_list'),
    path('worker_new/', views.worker_new, name='worker_new'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('level_list/', views.level_list, name='level_list'),
    path('level/<int:pk>/', views.level_detail, name='level_detail'),
    path('user', views.user, name='user'),
    path('zapros_list', views.zapros_list, name='zapros_list'),
    path('zapros/new/', views.zapros_new, name='zapros_new'),
    path('zapros/detail/<int:pk>', views.zapros_detail, name='zapros_detail'),
    path('zapros/awaits/<int:pk>', views.zapros_awaits, name='zapros_awaits'),
    path('zapros/delete/<int:pk>/<str:token>', views.zapros_delete, name='zapros_delete'),
    path('items_list', views.items_list, name='items_list'),
    path('item_new/', views.item_new, name='item_new'),
    path('item_detail/<int:pk>', views.item_detail, name='item_detail'),
    path('toner_list', views.toner_list, name='toner_list'),
    path('toner/edit/<int:pk>', views.toner_edit, name='toner_edit'),
    path('history_list', views.history_list, name='history_list'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django import forms
from .choices import *
from django.utils.crypto import get_random_string
from datetime import datetime

class Laptop(models.Model):
    brand = models.ForeignKey('Brand', on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField('Модель', max_length=200, default='')
    company = models.CharField('Компания',
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    family = models.CharField('Тип Техники',
        max_length=2,
        choices=techChoice,
        default='t1',
    )
    inventNumber = models.CharField('Инвентаризационный Номер', max_length=200, default='')
    serialNumber = models.CharField('Серийный Номер', max_length=200, default='')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') '


class Brand(models.Model):
    name = models.CharField('Модель', max_length=200, default='')

    def publish(self):
        self.save()

    def __str__(self):
        return self.name

    
class Printer(models.Model):
    name = models.CharField(max_length=200, default='name')
    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber


class Shredder(models.Model):
    name = models.CharField(max_length=200, default='name')
    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber

class Television(models.Model):
    name = models.CharField(max_length=200, default='name')
    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber



class Condition(models.Model):
    name = models.CharField(max_length=200, default='name')
    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber

class Telephone(models.Model):
    name = models.CharField(max_length=200, default='name')
    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber



class Camera(models.Model):
    name = models.CharField(max_length=200, default='name')
    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber



class Dispenser(models.Model):
    name = models.CharField(max_length=200, default='name')

    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber

class Microwave(models.Model):
    name = models.CharField(max_length=200, default='name')

    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber

class Display(models.Model):
    name = models.CharField(max_length=200, default='name')

    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber

class Computer(models.Model):
    name = models.CharField(max_length=200, default='name')

    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber


class Document(models.Model):
    name = models.CharField(max_length=200, default='name')
    section = models.CharField(
        max_length=3,
        choices=sectionChoice,
        default='s1',
    )
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)
    reading = models.BooleanField('Чтение', default=False)
    adding = models.BooleanField('Добавление', default=False)
    change = models.BooleanField('Изменение', default=False)
    delete = models.BooleanField('Удаление', default=False)
    lead = models.BooleanField('Проведение', default=False)
    unlead = models.BooleanField('Отмена проведения', default=False)
    watch = models.BooleanField('Просмотр', default=False)
    edit = models.BooleanField('Редактирование', default=False)
    lead_redact = models.BooleanField('Изменение проведенных', default=False)
    check_delete = models.BooleanField('Пометка на удаление', default=False)
    uncheck_delete= models.BooleanField('Снятие пометки на удаление', default=False)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' ' + str(self.owner)

class Worker(models.Model):
    name = models.CharField(max_length=200, default='')
    surname = models.CharField(max_length=200, default='')
    email = models.CharField(max_length=200, default='')
    server = models.CharField(max_length=200, default='')
    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )

    job = models.CharField(
        max_length=2,
        choices=jobChoice,
        default='pd',
    )


    def publish(self):
        self.save()

    def __str__(self):
        return  self.name +' '+ self.surname

class Zapros(models.Model):
    name = models.CharField('Почта',max_length=200, default='')
    problem = models.TextField('Опишите проблему',max_length=200, default='')
    unique_id = get_random_string(length=32)
    verification = models.CharField(unique_id, max_length=200, default = unique_id)
    status = models.CharField('Статус', max_length=200, default = 'new')
    def publish(self):
        self.save()

    def __str__(self):
        return self.name

class Finished(models.Model):
    name = models.CharField(max_length=200, default='name')
    problem = models.CharField(max_length=200, default='problem')


    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' ' + self.problem

class Toner(models.Model):
    name = models.CharField('Тонер',
        max_length=2,
        choices=tonerChoice,
        default='t1',
    )
    remained_loads = models.IntegerField('Осталось заправок', default=1)
    used_loads = models.IntegerField('Использовано сейчас', default=0)
    overall = models.IntegerField('Итого', default=1)
    accept = models.CharField('Совместимые', max_length=100, default='')
    

    def publish(self):
        self.save()

    def __str__(self):

blog/forms.py
from django import forms

from .models import *

class PostForm(forms.ModelForm):

    class Meta:
        model = Zapros
        fields = ('name', 'problem',)


class LaptopForm(forms.ModelForm):

    class Meta:
        model = Laptop
        fields = ('brand', 'name', 'family', 'company', 'inventNumber', 'serialNumber', 'owner')

class WorkerForm(forms.ModelForm):

    class Meta:
        model = Worker
        fields = ('name', 'surname', 'company', 'job')


class TonerForm(forms.ModelForm):

    class Meta:
        model = Toner
        fields = ('used_loads',)

class WorkerForm(forms.ModelForm):

    class Meta:
        model = Worker
        fields = ('name',)

blog/templates/blog/base.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script>

                function setBlock(elements){
                    for(var i=0;i<elements.length;i++){
                        elements[i].style.display="block";
                    }
                }
            
                function setNone(elements){
                    for(var i=0;i<elements.length;i++){
                        elements[i].style.display="none";
                    }
                }
            
                function check(){
                    setNone(document.getElementsByClassName('post'));
                    let input = document.getElementById('input').value.replace(/ ./g,"").replace(/\./g,'');
                    document.getElementById(input).style.display = "block";
                    // console.log(input);
                    }
                function fullList(){
                    setBlock(document.getElementsByClassName('post'));
                }
            
                (function() {
                    let url = location.href.match('#(.*)')[1];
                    document.getElementById('input').value = url;    
                    check();    
                })();
            
                function blok_open(current){
                    element = document.getElementById('content' + current);
                    if(element.className.match('opened')){
                        document.getElementById('content' + current).className -= 'opened';
                    }
                    else{
                        document.getElementById('content' + current).className += 'opened';
                    }
                }
            
                
        </script>
    </head>
    <body>
        <div class="container">
            
            {% if user.is_authenticated %}
                <div class="header">
                    <a class='btn btn-info'href="{% url 'zapros_list' %}">Список Запросов</a>
                    <a class='btn btn-info'href="{% url 'worker_list' %}">Список Сотрудников</a>
                    <a class='btn btn-info'href="{% url 'items_list' %}">Инвентарь</a>
                    <a class='btn btn-info'href="{% url 'toner_list' %}">Тонеры</a>
                </div>
            {% endif %}
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

<script href="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/code.js' %}"></script>

blog/templates/blog/history_list.html
{% extends 'blog/base.html' %}
    {% block content %}
        {% if user.is_superuser %}
            <div class="history_list">

                <div class="row buttons">
                    <button class="btn btn-primary" id='4' onclick="toner_choice(this.id)" >Все</button>
                    <button class="btn btn-primary" id='1' onclick="toner_choice(this.id)" >TRHM102</button>
                    <button class="btn btn-primary" id='2' onclick="toner_choice(this.id)" >CE285A</button>
                    <button class="btn btn-primary" id='3' onclick="toner_choice(this.id)" >TRSUNIV</button>
                    <button class="btn btn-primary" id='5' onclick="toner_choice(this.id)" >T125-K</button>

                    <input type="text" id="month" placeholder="Месяц">
                    <button class="btn btn-warning" onclick="toner_date()">Найти</button>
                </div>
                <div class="row">
                    <div class="col-md-2 title">Имя: </div>
                    <div class="col-md-2 title">Использовано:</div>
                    <div class="col-md-3 title">Использовано Итого:</div>
                    <div class="col-md-2 title">Остаток:</div>
                    <div class="col-md-2 title">Дата</div>
                </div>

                <div class="toner" id="toner1" >
                    {% for item in items %}
                        {% if item.name == 'TRHM102' %}
                            <div class="row item day{{ item.date.day }} month{{ item.date.month }}">
                                <div class="col-md-2 title">{{ item.name }}</div>
                                <div class="col-md-2 title">{{ item.used }}</div>
                                <div class="col-md-3 title">{{ item.new_over }}</div>
                                <div class="col-md-2 title">{{ item.new_rem }}</div>
                                <div class="col-md-3 title">{{ item.date.day }}.{{ item.date.month }}</div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="toner" id="toner2">
                    {% for item in items %}
                        {% if item.name == 'CE285A' %}
                            <div class="row item day{{ item.date.day }} month{{ item.date.month }}">
                                <div class="col-md-2 title">{{ item.name }}</div>
                                <div class="col-md-2 title">{{ item.used }}</div>
                                <div class="col-md-3 title">{{ item.new_over }}</div>
                                <div class="col-md-2 title">{{ item.new_rem }}</div>
                                <div class="col-md-3 title">{{ item.date.day }}.{{ item.date.month }}</div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>

                <div class="toner" id="toner3">
                    {% for item in items %}
                        {% if item.name == 'TRSUNIV' %}
                            <div class="row item day{{ item.date.day }} month{{ item.date.month }}">
                                <div class="col-md-2 title">{{ item.name }}</div>
                                <div class="col-md-2 title">{{ item.used }}</div>
                                <div class="col-md-3 title">{{ item.new_over }}</div>
                                <div class="col-md-2 title">{{ item.new_rem }}</div>
                                <div class="col-md-3 title">{{ item.date.day }}.{{ item.date.month }}</div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="toner" id="toner5">
                    {% for item in items %}
                        {% if item.name == 'T125-K' %}
                            <div class="row item day{{ item.date.day }} month{{ item.date.month }}">
                                <div class="col-md-2 title">{{ item.name }}</div>
                                <div class="col-md-2 title">{{ item.used }}</div>
                                <div class="col-md-3 title">{{ item.new_over }}</div>
                                <div class="col-md-2 title">{{ item.new_rem }}</div>
                                <div class="col-md-3 title">{{ item.date.day }}.{{ item.date.month }}</div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>

            </div>
        {% endif %}


    {% endblock %}

blog/templates/blog/item_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="item_detail">
        <div class="header">
        </div>
            <div class="row">
                {% for item in items %}
                    <div class="label"> Модель: </div>{{ item.name }} <br>
                    <div class="label"> Серийный Номер: </div>{{ item.serialNumber }}<br>
                    <div class="label"> Инв. Номер: </div>{{ item.inventNumber }}<br>
                    <div class="label"> Пользователь: </div>{{ item.owner }}<br>

                {% endfor %}
            </div>
    </div>
{% endblock %}

blog/templates/blog/items_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="items_list">
        <div class="header">
            <a href="{% url 'item_new' %}" class='glyphicon glyphicon-plus'>+</a>
            Добавить новую технику
        </div>
        <div class="row buttons">
            <button class="btn btn-primary" id="Ноутбук" onclick="family_choice(this.id)">Ноутбуки</button>
            <button class="btn btn-primary" id="Компьютер" onclick="family_choice(this.id)">Компьютеры</button>
            <button class="btn btn-primary" id="Монитор" onclick="family_choice(this.id)">Мониторы</button>
            <button class="btn btn-primary" id="Принтер" onclick="family_choice(this.id)">Принтеры</button>

            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Компания
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <a class="dropdown-item" id="all" onclick="company_choice(this.id)">Все</a>
                    <a class="dropdown-item" id="Planeta Doors" onclick="company_choice(this.id)">Planeta Doors</a>
                    <a class="dropdown-item" id="Beltaus Trading" onclick="company_choice(this.id)">Beltaus</a>
                </div>
            </div>
            <!-- <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Производитель
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
                        <a class="dropdown-item" id="all" onclick="company_choice(this.id)">Все</a>
                        <a class="dropdown-item" id="Planeta Doors" onclick="company_choice(this.id)">Planeta Doors</a>
                        <a class="dropdown-item" id="Beltaus Trading" onclick="company_choice(this.id)">Beltaus</a>
                    </div>
                </div> -->
            <button class="btn btn-success" onclick="apply()">Применить</button>
            
        </div>
        <div class="row list" id="list">
            {% for item in items %}
                <!-- <a href="{% url 'item_detail' item.pk %}" class="col-md-4 btn btn-warning">
                </a> -->
                <a href="{% url 'item_detail' item.pk %}" class="item {{ item.get_family_display }} {{ item.get_company_display }}">
                    {{ item.brand }}
                    {{ item.name }}
                    {{ item.get_family_display }}
                    {{ item.get_company_display }}
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/level_detail.html
{% extends 'blog/base.html' %}
    {% block content %}
    <div class="name">{{ post }}</div>
    <br>
    <div class="title">Документы</div>
    <div class="row">
        {% for document in documents %}
            {% if post == document.owner and document.get_section_display == 'Документы'%}
                <div class="blok" id="{{ document.id }}" onclick="blok_open(this.id)">
                    <div class="name">
                        {{ document.name }}
                    </div>
                    <div class="content" id="content{{document.id}}">
                        <!-- <div class="section">
                            {{ document.fileName.get_section_display }}
                        </div> -->
                        {% if document.reading %}
                            Чтение
                        {% endif %}
                        {% if document.adding %}
                            Добавление
                        {% endif %}
                        {% if document.change %}
                            Изменение
                        {% endif %}
                        {% if document.delete %}
                            Удаление
                        {% endif %}
                        {% if document.lead %}
                            Изменение
                        {% endif %}
                        {% if document.unlead %}
                            Изменение
                        {% endif %}
                        {% if document.watch %}
                            Просмотр
                        {% endif %}
                        {% if document.edit %}
                            Изменение
                        {% endif %}
                        {% if document.lead_redact %}
                            Изменение
                        {% endif %}
                        {% if document.check_delete %}
                            Изменение
                        {% endif %}
                        {% if document.uncheck_delete %}
                            Изменение
                        {% endif %}
                        {% if document.edit %}
                            Редактирование
                        {% endif %}
                        <br>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/specific.html
{% extends 'blog/base.html' %}

{% block content %}

    <!-- <div class="headers">
        <div>name</div>
        <div>surname</div>
    </div> -->
    {% if user.is_authenticated %}
        <div class="row">
            {% for post in posts %}
            <div class="col-md-4 post"  id="{% if post.company == 'pd' %}001.{% elif post.company == 'ar' %}002.{% elif post.company == 'bt' %}003.{% elif post.company == 'ts' %}004.{% elif post.company == 'ki' %}005.{% elif post.company == 'co' %}006.{% else %}un.{% endif %}{{ post.job }}.{{ post.workerID }}.{{ post.laptop.inventNumber }}">
                <a href="{% url 'post_detail' pk=post.pk %}">
                    {{ post.name }}
                    {{ post.surname }}
                    <b>
                        {{ post.get_job_display }}
                    </b>
                        <div>asdasasd</div>
                        <div class="info">
                                {% if post.company == 'pd' %}
                                    001.
                                    {% elif post.company == 'ar' %}
                                        002.
                                        {% elif post.company == 'bt' %}
                                            003.
                                            {% elif post.company == 'ts' %}
                                                004.
                                                {% elif post.company == 'ki' %}
                                                    005.
                                                    {% elif post.company == 'co' %}
                                                        006.
                                                        {% else %}
                                                            un.
                                {% endif %}
                                {{ post.job }}.
                                {{ post.workerID }}.
                                {{ post.laptop.inventNumber }}
                                {{ post.id }}
                        </div>
                    {% if post.laptop.inventNumber == '?????' %}
                        <div class="red">
                            Нет инвентарьного номера
                        </div>
                    {% endif %}
                </a>
            </div>
            {% endfor %}
        </div>

    <a href="/">List</a>
    {% else %}
    <a href="/accounts/login/">Login</a>
    {% endif %}
{% endblock %}

blog/templates/blog/worker_list.html
{% extends 'blog/base.html' %}

{% block content %}

    <!-- <div class="headers">
        <div>name</div>
        <div>surname</div>
    </div> -->

    {% if user.is_authenticated %}
        <div class="post_list">
            <div class="top">
                <input type="text" id="input" >
                <button class="btn" onclick="check()">Check</button>
                <button class="btn" onclick="fullList()">Full list</button>
                <a href="{% url 'worker_new' %}" class='glyphicon glyphicon-plus'></a>

            </div>
            {% if worker_count %}
                Cотрудники <b> {{ worker_count }} </b>
            {% endif %}<br>
            {% if laptop_count %}
                Ноутбуки  <b> {{ laptop_count }} </b>
            {% endif %}


            <div class="row">
                {% for post in posts %}
                <div class="col-md-4 post list"  id="{% if post.company == 'pd' %}001{% elif post.company == 'ar' %}002{% elif post.company == 'bt' %}003{% elif post.company == 'ts' %}004{% elif post.company == 'ki' %}005{% elif post.company == 'co' %}co{% else %}un{% endif %}{{ post.job }}{{ post.workerID }}">
                    <a href="{% url 'post_detail' pk=post.pk %}">
                        {{ post.name }}
                        {{ post.surname }}
                        <b>
                            {{ post.get_job_display }}
                        </b>
                            <div class="info">
                                    {% if post.company == 'pd' %}
                                        001.
                                        {% elif post.company == 'ar' %}
                                            002.
                                            {% elif post.company == 'bt' %}
                                                003.
                                                {% elif post.company == 'ts' %}
                                                    004.
                                                    {% elif post.company == 'ki' %}
                                                        005.
                                                        {% elif post.company == 'co' %}
                                                            co.
                                                            {% else %}
                                                                un.
                                    {% endif %}
                                    {{ post.job }}.
                                    {{ post.pk }}
                            </div>
                        {% if post.laptop.inventNumber == '?????' %}
                            <div class="red">
                                Нет инвентарьного номера
                            </div>
                        {% endif %}
                    </a>
                </div>
                {% endfor %}
            </div>
        {% else %}
            <a href="/accounts/login/">Login</a>
        {% endif %}

    </div>
{% endblock %}